describe('Swaglab Website demo',function()
{  
     //negative scenario
    it('Login id with invalid username and password',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('sowbarnya')
        cy.get('[id="password"]').type('muthusamy')
        cy.get('[id="login-button"]').click()
        cy.get('#login_button_container > div > form > div.error-message-container.error > h3')
        .should('be.visible')
        cy.get('#login_button_container > div > form > div.error-message-container.error > h3')
        .should('contain','Epic sadface: Username and password do not match any user in this service')
    })
    //negative scenario
    it('Login without username and password',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('[id="login-button"]').click()
        cy.get('#login_button_container > div > form > div.error-message-container.error > h3')
        .should('be.visible')
        cy.get('#login_button_container > div > form > div.error-message-container.error > h3')
        .should('contain','Epic sadface: Username is required')
    })
    //positive scenario
    it('login with valid username and password for id 1',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
    })
    it('login with valid username and password for id 2',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('locked_out_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#login_button_container > div > form > div.error-message-container.error')
        .should('be.visible').and('contain','Epic sadface: Sorry, this user has been locked out.')
    })
it('login with valid username and password for id 3',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('problem_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
    })
    it('login with valid username and password for id 4',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('problem_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
    })
    //Add to cart for id 1
    it('Add to cart for id1 name(high to low)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Price (high to low)')
        cy.contains('Price (high to low)').should('be.visible')
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('[id="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
    })
    it('Add to cart for id1 name(low to high)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Price (low to high)')
        cy.contains('Price (low to high)').should('be.visible')
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('[id="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
    })
it('Add to cart for id1 name(Z-A)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Name (Z to A)')
        cy.contains('Name (Z to A)').should('be.visible')
        cy.get('[id="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-backpack').click() 
    })
    it('Add to cart for id1 name(A-Z)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Name (A to Z)')
        cy.contains('Name (A to Z)').should('be.visible')
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('[id="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
    })
    // ADd to cart for id 3
    it('Add to cart for id 3 name(A-Z)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('problem_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Name (A to Z)')
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
    })  
    it('Add to cart for id 3 name(Z-A)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('problem_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click() 
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Name (Z to A)')
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-backpack').click() 
    })
it('Add to cart for id 3 name(low to high)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('problem_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()  
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Price (low to high)')
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click() 
    })  
    it('Add to cart for id 3 name(high to low)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('problem_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click() 
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Price (high to low)')
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
    })    
    //add to cart for id 4
   it('Add to cart for id4 name(high to low)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Price (high to low)')
        cy.contains('Price (high to low)').should('be.visible')
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('[id="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
    })
it('Add to cart for id4 name(low to high)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Price (low to high)')
        cy.contains('Price (low to high)').should('be.visible')
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('[id="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
    })
    it('Add to cart for id4 name(Z-A)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Name (Z to A)')
        cy.contains('Name (Z to A)').should('be.visible')
        cy.get('[id="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-backpack').click() 
    })
    it('Add to cart for id4 name(A-Z)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Name (A to Z)')
        cy.contains('Name (A to Z)').should('be.visible')
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('[id="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
    })
//amount calculation for user id 1,id3 and id4
    it('Amount calculation for userid1(A-Z)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Name (A to Z)')
        cy.contains('Name (A to Z)').should('be.visible')
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('[id="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
        cy.get('#shopping_cart_container > a').click()
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(3) > div.cart_item_label')
        .should('be.visible').and('contain','$29.99')
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(4) > div.cart_item_label')
        .should('be.visible').and('contain','$9.99')
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(5) > div.cart_item_label')
        .should('be.visible').and('contain','$15.99')
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(6) > div.cart_item_label')
        .should('be.visible').and('contain','$49.99')
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(7) > div.cart_item_label')
        .should('be.visible').and('contain','$7.99')
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(8) > div.cart_item_label')
        .should('be.visible').and('contain','$15.99')
        cy.get('#checkout').click()
        cy.get('#first-name').type('sowbarnya')
        cy.get('#last-name').type('muthusamy')
        cy.get('#postal-code').type(638315)
        cy.get('#continue').click()
        cy.url().should('include','checkout-step-two')
        cy.get('.summary_total_label').should('be.visible').and('contain','$140.34')
        cy.wait(2000)
    })
    //Amount calculation 
    it('Amount calculation for id3problem user(A-Z)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Name (A to Z)')
        cy.contains('Name (A to Z)').should('be.visible')
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('#shopping_cart_container > a').click()
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(3) > div.cart_item_label')
        .should('be.visible').and('contain','$29.99')
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(4) > div.cart_item_label')
        .should('be.visible').and('contain','$9.99')
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(5) > div.cart_item_label')
        .should('be.visible').and('contain','$7.99')
        cy.get('#checkout').click()
        cy.get('#first-name').type('sowbarnya')
        cy.get('#last-name').type('muthusamy')
        cy.get('#postal-code').type(638315)
        cy.get('#continue').click()
        cy.url().should('include','checkout-step-two')
        cy.get('.summary_total_label').should('be.visible').and('contain','$51.81')
        cy.wait(2000)
    })
//Amount calculation
    it('Amount calculation for username4(A to Z)',function()
    {
        cy.visit('https://www.saucedemo.com/') 
        cy.get('input[id="user-name"]').type('standard_user')
        cy.get('[id="password"]').type('secret_sauce')
        cy.get('[id="login-button"]').click()
        cy.get('#header_container > div.header_secondary_container > div.right_component > span > select')
        .select('Name (A to Z)')
        cy.contains('Name (A to Z)').should('be.visible')
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('#add-to-cart-sauce-labs-bolt-t-shirt').click()
        cy.get('#add-to-cart-sauce-labs-fleece-jacket').click()
        cy.get('#add-to-cart-sauce-labs-onesie').click()
        cy.get('[id="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
        cy.get('#shopping_cart_container > a').click()
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(3) > div.cart_item_label')
        .should('be.visible').and('contain','$29.99')
        cy.get('#cart_contents_container > div > div.cart_list > div:nth-child(4) > div.cart_item_label')
        .should('be.visible').and('contain','$9.99')
        cy.get('#checkout').click()
        cy.get('#first-name').type('sowbarnya')
        cy.get('#last-name').type('muthusamy')
        cy.get('#postal-code').type(638315)
        cy.get('#continue').click()
        cy.url().should('include','checkout-step-two')
        cy.get('.summary_total_label').should('be.visible').and('contain','$140.34')
        cy.wait(2000)
    })
})

