Cypress.on('uncaught:exception',(err,runnable) =>{
    return false
})
describe('UltimateQA Course details',function()
{
    //About us page
    it('about page in ultimateQA',function(){
        cy.visit('https://ultimateqa.com/about/')
        cy.get('#header-sec > div > div > div > div > div.et_pb_menu__logo-wrap').should('be.visible').click()
        cy.get('.wp-image-215556').should('be.visible')
        cy.get('#menu-home-page-menu > .et_pb_menu_page_id-216155 > a')
        .should('have.attr', 'href').and('include', 'https://courses.ultimateqa.com/collections')
        cy.get('#menu-home-page-menu > .et_pb_menu_page_id-216153 > a')
        .should('have.attr', 'href').and('include', 'https://ultimateqa.com/selenium-webdriver-java-course/' )
        cy.get('#menu-home-page-menu > .et_pb_menu_page_id-216154 > a')
        .should('have.attr', 'href').and('include', 'https://courses.ultimateqa.com/courses/selenium-with-c')
        cy.get('#menu-home-page-menu > .et_pb_menu_page_id-6838 > a')
        .should('have.attr', 'href').and('include', 'https://ultimateqa.com/best-selenium-webdriver-resources/')
        cy.get('#menu-home-page-menu > .et_pb_menu_page_id-507 > a')
        .should('have.attr', 'href').and('include', 'https://ultimateqa.com/automation/')
        cy.get('#menu-home-page-menu > .et_pb_menu_page_id-216855 > a')
        .should('have.attr', 'href').and('include', 'https://ultimateqa.com/consulting/')
        cy.get('#menu-home-page-menu > .et_pb_menu_page_id-213448 > a')
        .should('have.attr', 'href').and('include', 'https://ultimateqa.com/blog/')
        cy.get('.et_pb_text_0 > .et_pb_text_inner > h1').contains( 'Nikolay Advolodkin')
        cy.get('.et_pb_text_1 > .et_pb_text_inner > :nth-child(2)').contains('IT Professional')
        cy.get('.et_pb_text_1 > .et_pb_text_inner > :nth-child(3)').contains('Selenium WebDriver')
        cy.get('.et_pb_text_3 > .et_pb_text_inner > h1').contains('Case Studies')
        cy.get('#et_pb_contact_name_0').should('be.visible').type('Sowbarnya')
        cy.get('#et_pb_contact_email_0').should('be.visible').type('sowbarnya@gmail.com')
        cy.get('#et_pb_contact_message_0').should('be.visible').type('QAoncloud software tester')
        cy.get('.et_pb_contact_submit').should('be.visible')
        cy.get('.wp-image-5115').should('be.visible')
        cy.get('.wp-image-5116').should('be.visible')
        cy.get('.wp-image-5117').should('be.visible')
        cy.get('.wp-image-5118').should('be.visible') 
        cy.get('.et_pb_social_media_follow_network_0 > .icon').should('be.visible').click()
        cy.go('back')
        cy.wait(3000)
    })
    it('about page youtube icon',function(){
        cy.visit('https://ultimateqa.com/about/')
        cy.wait(2000)
        cy.get('.et_pb_social_media_follow_network_2 > .icon').should('be.visible').click()
        cy.go('back') 
    })
it('about page twitter icon',function(){
        cy.visit('https://ultimateqa.com/about/')
        cy.wait(2000)
        cy.get('.et_pb_social_media_follow_network_1 > .icon')
        .should('be.visible').click()
        cy.go('back')
    }) 
    it('about page facebook icon',function(){
        cy.visit('https://ultimateqa.com/about/')
        cy.wait(2000)
        cy.get('.et_pb_social_media_follow_network_3 > .icon').should('be.visible').click()
        cy.go('back')
    })
    it('About us page footer',function(){
        cy.visit('https://ultimateqa.com/consulting/')
        cy.get('#menu-item-3331 > a').should('have.attr', 'href')
        .and('include', 'https://ultimateqa.com/about/')
        cy.get('#menu-item-216747 > a').should('have.attr', 'href')
        .and('include', 'https://ultimateqa.com/affiliate/')
        cy.get('#menu-item-216867 > a').should('have.attr', 'href')
        .and('include', 'https://ultimateqa.com/consulting/')
        cy.get('#menu-item-215228 > a').should('have.attr', 'href')
        .and('include', 'youtube.com/channel/UCVZXj9vKyZ6L2OakzRH2aOQ')
        cy.get('#menu-item-215229 > a').should('have.attr', 'href')
        .and('include', 'https://www.facebook.com/Ultimateqa1/')
        cy.get('#menu-item-216842 > a').should('have.attr', 'href')
        .and('include', 'https://ultimateqa.com/contact/')
 })
 //Consulting services page  
 it('Consulting service in ultimateQA ',function(){
    //header menu
    cy.visit('https://ultimateqa.com/consulting/')
    cy.get('#header-sec > div > div > div > div > div.et_pb_menu__logo-wrap').should('be.visible').click()
    cy.get('#menu-home-page-menu > .et_pb_menu_page_id-216155 > a')
    .should('have.attr', 'href').and('include', 'https://courses.ultimateqa.com/collections')
    cy.get('#menu-home-page-menu > .et_pb_menu_page_id-216153 > a')
    .should('have.attr', 'href').and('include', 'https://ultimateqa.com/selenium-webdriver-java-course/' )
    cy.get('#menu-home-page-menu > .et_pb_menu_page_id-216154 > a')
    .should('have.attr', 'href').and('include', 'https://courses.ultimateqa.com/courses/selenium-with-c')
    cy.get('#menu-home-page-menu > .et_pb_menu_page_id-6838 > a')
    .should('have.attr', 'href').and('include', 'https://ultimateqa.com/best-selenium-webdriver-resources/')
    cy.get('#menu-home-page-menu > .et_pb_menu_page_id-507 > a')
    .should('have.attr', 'href').and('include', 'https://ultimateqa.com/automation/')
    cy.get('#menu-home-page-menu > .et_pb_menu_page_id-216855 > a')
    .should('have.attr', 'href').and('include', 'https://ultimateqa.com/consulting/')
    cy.get('#menu-home-page-menu > .et_pb_menu_page_id-213448 > a')
    .should('have.attr', 'href').and('include', 'https://ultimateqa.com/blog/')
})
it('Consulting services content',function(){
    //content page
    cy.visit('https://ultimateqa.com/consulting/')
    cy.get('.et_pb_section_0 > .et_pb_module > .et_pb_fullwidth_header_container > .header-content-container > .header-content > .et_pb_module_header')
    .contains('Framework Assessments & Testing Consulting')
    cy.get('.et_pb_section_0 > .et_pb_module > .et_pb_fullwidth_header_container > .header-content-container > .header-content > .et_pb_header_content_wrapper > p')
    .contains('Unparalleled testing consulting that can drastically transform your digital confidence!')
    //Learn more
    cy.get('.et_pb_column_2 > .et_pb_button_module_wrapper > .et_pb_button').click()
    cy.get('.et_pb_column_3 > .et_pb_button_module_wrapper > .et_pb_button').click() 
    cy.get('.et_pb_section_3 > .et_pb_module > .et_pb_fullwidth_header_container > .header-content-container > .header-content > .et_pb_module_header')
    .contains('Digital Confidence')
    cy.get('.header-content > .et_pb_button').click()
    cy.get('.et_pb_testimonial_0 > .et_pb_testimonial_description > .et_pb_testimonial_meta > .et_pb_testimonial_company > a')
    .should('have.attr', 'href')
    .and('include', 'https://devops.com/4-steps-to-achieve-a-66-reduction-in-test-run-time/')
    cy.get('.et_pb_with_border > .et_pb_testimonial_description > .et_pb_testimonial_meta > .et_pb_testimonial_company > a')
    .should('have.attr', 'href')
    .and('include', 'https://saucelabs.com/blog/1-simple-trick-to-massively-improve-automation-efficiency')
    cy.get('.et_pb_testimonial_3 > .et_pb_testimonial_description > .et_pb_testimonial_meta > .et_pb_testimonial_company > a')
    .should('have.attr', 'href')
    .and('include', 'https://saucelabs.com/blog/how-to-optimize-a-test-and-make-it-560-percent-faster')
    cy.get('#et_pb_contact_name_0').type('Sowbarnya')
    cy.get('#et_pb_contact_email_0').type('Sowbarnya@gmail.com')
    cy.get('#et_pb_contact_companyname_0').type('Qaoncloud')
    cy.get('#et_pb_contact_message_0').type('Software tester')
    cy.get('#et_pb_contact_message_0').should('be.visible')
})
it('consulting service footer',function(){
    cy.visit('https://ultimateqa.com/consulting/')
    cy.get('#menu-item-3331 > a').should('have.attr', 'href')
    .and('include', 'https://ultimateqa.com/about/')
    cy.get('#menu-item-216747 > a').should('have.attr', 'href')
    .and('include', 'https://ultimateqa.com/affiliate/')
    cy.get('#menu-item-216867 > a').should('have.attr', 'href')
    .and('include', 'https://ultimateqa.com/consulting/')
    cy.get('#menu-item-215228 > a').should('have.attr', 'href')
    .and('include', 'youtube.com/channel/UCVZXj9vKyZ6L2OakzRH2aOQ')
    cy.get('#menu-item-215229 > a').should('have.attr', 'href')
    .and('include', 'https://www.facebook.com/Ultimateqa1/')
    cy.get('#menu-item-216842 > a').should('have.attr', 'href')
    .and('include', 'https://ultimateqa.com/contact/')
})
})

